[package]
name = "slithergen"
version = "0.1.0"
edition = "2024"

[dependencies]
argh = "0.1.13"
open = "5.3.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"

[dev-dependencies]
googletest = "0.14.2"
tempfile = "3.24.0"
